<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library [
    <!ELEMENT library (book+)>
    <!ELEMENT book (title, author, year, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT price (#PCDATA)>

    <!ATTLIST book category CDATA #REQUIRED>
    <!ATTLIST price currency CDATA #REQUIRED>
]>
<library>
    <book category="Fiction">
        <title>The Great Gatsby</title>
        <author>F. Scott Fitzgerald</author>
        <year>1925</year>
        <price currency="USD">12.99</price>
    </book>
    <book category="Science Fiction">
        <title>Dune</title>
        <author>Frank Herbert</author>
        <year>1965</year>
        <price currency="USD">14.95</price>
    </book>
</library>
